name: CI Workflow
on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: [master]

jobs:
  build-project:
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'Apicurio'
    steps:
      - name: Checkout Code with Ref '${{ github.ref }}'
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 8
          architecture: x64

      - name: Build Project
        run: ./mvnw clean install

     # - name: Google Chat Notification
     #   if: ${{ failure() }}
     #   uses: Co-qn/google-chat-notification@releases/v1
     #   with:
     #     name: ${{ github.workflow }}
     #     url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
     #     status: ${{ job.status }}
